module.exports = {
  itemsArray: [
    {
      id: "kingskin",
      name: "King Skin",
      type: "normal",
      kind: "skin",
      creator: "Theocharis",
      story: "An old skin, existed in old Stick Surf versions!",
    },
    {
      id: "snowskin",
      name: "Snow Skin",
      type: "normal",
      kind: "skin",
      creator: "Theocharis",
      story: "An old skin, made in snowy days..",
    },
    {
      id: "spartaskin",
      name: "Spartan Skin",
      type: "normal",
      kind: "skin",
      creator: "Theocharis",
      story:
        "An old skin, created to honor the battle of the Spartans versus the Persians!",
    },
    {
      id: "planecrashskin",
      name: "Plane Crash Skin",
      type: "normal",
      kind: "skin",
      creator: "Aldo Tanku",
      story:
        "A skin made for people who played Plane Crash ( a game by Aldo Tanku )",
    },
    {
      id: "rainbowskin",
      name: "Rainbow Skin",
      type: "normal",
      kind: "skin",
      creator: "Theocharis",
      story:
        "A skin made for people who like rainbow color, NOT because it supports homosexuality, but because the colors are pretty cool",
    },
    {
      id: "bombskin",
      name: "Bomb Skin",
      type: "normal",
      kind: "skin",
      creator: "Theocharis",
      story:
        "An old skin, created to seal the fact that almost every game has some bombs in it",
    },
    {
      id: "xmassurfboard",
      name: "Xmas Surfboard",
      type: "normal",
      kind: "surfboard",
      creator: "Theocharis",
      story:
        "An old surfboard, created in the first xmas of Stick Surf's existance!",
    },
    {
      id: "goldensurfboard",
      name: "Golden Surfboard",
      type: "normal",
      kind: "surfboard",
      creator: "Theocharis",
      story: "An old surfboard, made of gold!",
    },
    {
      id: "sesiskin",
      name: "Sexy Skin",
      type: "normal",
      kind: "skin",
      creator: "Theocharis",
      story: "A sexy skin, nothing more or less!",
    },
    {
      id: "fancysurfboard",
      name: "Fancy Surfboard",
      type: "normal",
      kind: "surfboard",
      creator: "Theocharis",
      story: "A fancy surfboard, for those who enjoy the attractive colors :3",
    },
    {
      id: "teamsurfboard",
      name: "Team Surfboard",
      type: "normal",
      kind: "surfboard",
      creator: "Theocharis",
      story: "A nice board, people equip it to honor the Stick Surf Team!",
    },
    {
      id: "policehat",
      name: "Police Hat",
      type: "normal",
      kind: "hat",
      creator: "Albert Avagyan",
      story:
        "A cap created by Albert and given to the Stick Surf Team for use in-game. Thats a nice cap don't you think?",
    },
    {
      id: "bloodyeyeskin",
      name: "Bloody Eye Skin",
      type: "normal",
      kind: "skin",
      creator: "Theocharis",
      story:
        "A bloody skin, for all the bloody tears that people came through getting scammed",
    },
    {
      id: "xmasskin",
      name: "Xmas Skin",
      type: "normal",
      kind: "skin",
      creator: "Olive",
      story: "This was created for the 2014 xmas, and was the best skin evar!",
    },
    {
      id: "alienskin",
      name: "Alien Skin",
      type: "normal",
      kind: "skin",
      creator: "Albert Avagyan",
      story: "Old skin, aliens exist:o",
    },
    {
      id: "aliensurfboard",
      name: "Alien Surfboard",
      type: "normal",
      kind: "surfboard",
      creator: "Albert Avagyan",
      story: "Old surfboard, aliens exist:o",
    },
    {
      id: "skullsurfboard",
      name: "Skull Surfboard",
      type: "normal",
      kind: "surfboard",
      creator: "Unknown",
      story:
        "Nice surfboard, if you surf a lot, thats what you get... getting skulled",
    },
    {
      id: "wizzyhat",
      name: "Wizzy Hat",
      type: "normal",
      kind: "hat",
      creator: "Unknown",
      story: "A beautiful cap, for all the witches playing Stick Surf",
    },
    {
      id: "piratehat",
      name: "Pirate Hat",
      type: "normal",
      kind: "hat",
      creator: "Unknown",
      story:
        "Surfing Piracy is happening a lot these days, scammers, buggers, hackers, ugh.. we need a cap for them",
    },
    {
      id: "kinghat",
      name: "King Hat",
      type: "premium",
      kind: "hat",
      creator: "Unknown",
      story:
        "This is the first premium ever released in Stick Surf, it was very rare and nice! Now everyone almost have it since its price dropped a lot with many purchases and giveaways!",
    },
    {
      id: "furbyskin",
      name: "Furby Skin",
      type: "premium",
      kind: "skin",
      creator: "Olive",
      story:
        "This is the first premium skin ever released in Stick Surf, it was very rare and nice! Now everyone almost have it since its price dropped a lot with many purchases and giveaways!",
    },
    {
      id: "gentlehat",
      name: "Gentle Hat",
      type: "normal",
      kind: "hat",
      creator: "Unknown",
      story: "A nice masterpiece, very beautiful to be just a normal item :')",
    },
    {
      id: "freezyhat",
      name: "Freezy Hat",
      type: "normal",
      kind: "hat",
      creator: "Unknown",
      story: "The weather was messy when this item was released, yeah very cold!",
    },
    {
      id: "xmashat",
      name: "2014 Xmas Hat",
      type: "normal",
      kind: "hat",
      creator: "Unknown",
      story: "The hat that was worn in 2014's xmas time!",
    },
    {
      id: "sharpknives",
      name: "Sharp Knives",
      type: "normal",
      kind: "hand",
      creator: "Sandro Kach.",
      story:
        "Two blades, the best normal item ever existed back in the old days. The creator was Sandro that now isn't in Stick Surf Team... Those blades were awesome m8!",
    },
    {
      id: "xmascandy",
      name: "2014 Xmas Candy",
      type: "normal",
      kind: "hand",
      creator: "Unknown",
      story: "A candy, eaten in the 2014's xmas time!",
    },
    {
      id: "gasmask",
      name: "Gas Mask",
      type: "normal",
      kind: "hat",
      creator: "Theocharis",
      story:
        "This mask was the uggliest item ever in Stick Surf, as many people said. It made people actually throw out gas by seeing it, and it was redesigned and eventually replaced by this current look (we don't show the old look for your own health!)",
    },
    {
      id: "anonmask",
      name: "Anon Mask",
      type: "normal",
      kind: "hat",
      creator: "Theocharis",
      story:
        "This mask was really ugly, just as the old gasmask.. and it was redesigned to be same as the Stick Run's anonymous mask.",
    },
    {
      id: "homelesshat",
      name: "Homeless Hat",
      type: "normal",
      kind: "hat",
      creator: "Theocharis",
      story:
        "A very old hat, Theo's favourite item back in the old days... It should be normal so everyone could have it, its so awesome!",
    },
    {
      id: "sticksurfcap",
      name: "Stick Surf Cap",
      type: "normal",
      kind: "hat",
      creator: "Unknown",
      story: "An old cap, for all those Stick Surf Fans :)",
    },
    {
      id: "theocap",
      name: "Theo Cap",
      type: "normal",
      kind: "hat",
      creator: "Iyed BHD",
      story:
        "This item was designed by Iyed, an ex-SRT member, and Theocharis added a T on it because he loved it. It is an item, to wear if you love Theo <3 xD",
    },
    {
      id: "chinacap",
      name: "China Cap",
      type: "normal",
      kind: "hat",
      creator: "Sandro Kach.",
      story:
        "This item was one of the great Sandro Designs. Its a really nice hat to wear if you're a chinese :)",
    },
    {
      id: "axe",
      name: "Axe",
      type: "normal",
      kind: "hand",
      creator: "Unknown",
      story:
        "This item was the first axe to be released in Stick Surf. There are some secrets about this one that none knows!",
    },
    {
      id: "teslacannon",
      name: "Tesla Cannon",
      type: "normal",
      kind: "hand",
      creator: "Unknown",
      story: "The first gun-like item for Stick Surf.",
    },
    {
      id: "punishermask",
      name: "Punisher Mask",
      type: "rare",
      kind: "hat",
      creator: "Lazar Krstic",
      story:
        "The first rare item type for Stick Surf, used to be very rare, but now is shared a lot!",
    },
    {
      id: "yellowgloves",
      name: "Yellow Gloves",
      type: "premium",
      kind: "hand",
      creator: "Manuel Otto",
      story:
        "This was the first item to be displayed in the Old Stick Surf (2012-2013) but then it was removed in the newer Stick Surf, and added again later. So its not considered as the first premium.",
    },
    {
      id: "dragonskin",
      name: "Dragon Skin",
      type: "normal",
      kind: "skin",
      creator: "Theocharis",
      story: "It was a pride to equip this skin.",
    },
    {
      id: "eagleskin",
      name: "Eagle Skin",
      type: "normal",
      kind: "skin",
      creator: "Theocharis",
      story: "The first skin displaying a bird in Stick Surf xD!",
    },
    {
      id: "stickrunskin",
      name: "Stick Run Skin",
      type: "normal",
      kind: "skin",
      creator: "Theocharis",
      story:
        "A skin created by the Stick Surf developer to honor the Stick Run Developer and peace out, because the games was thought to be in war!",
    },
    {
      id: "stickcombatskin",
      name: "Stick Combat Skin",
      type: "normal",
      kind: "skin",
      creator: "Theocharis",
      story:
        "A skin created by the Stick Surf developer to honor the Stick Combat Developer and peace out, because the games was thought to be in war!",
    },
    {
      id: "slayerhead",
      name: "Slayer Mask",
      type: "premium",
      kind: "hat",
      creator: "Unknown",
      story: "A very beautiful item, combines some anime hair with a mask!",
    },
    {
      id: "slayerknife",
      name: "Slayer Knife",
      type: "premium",
      kind: "hand",
      creator: "Unknown",
      story:
        "Looks perfect on the surfer, the Stick Surf developer considers it as the best item for hand-use!",
    },
    {
      id: "coldhat",
      name: "Cold Hat",
      type: "rare",
      kind: "hat",
      creator: "Unknown",
      story:
        "Another 2014 xmas item, was created to avoid the cold and keep surfing!",
    },
    {
      id: "verifiedskin",
      name: "Verified Item",
      type: "premium",
      kind: "skin",
      creator: "Theocharis",
      story:
        "An item in premium shop, which enables you to have a verified badge displayed instead of your level, and gives you the ability to wear the Verified Skin.",
    },
    {
      id: "teamskin",
      name: "Team Skin",
      type: "premium",
      kind: "skin",
      creator: "Theocharis",
      story:
        "An item to display who is in the Stick Surf Team. They are the developers of the game <3!",
    },
    {
      id: "vipskinit",
      name: "Vip Skin",
      type: "premium",
      kind: "skin",
      creator: "Theocharis",
      story: "An item to display who is a VIP! That skin shines too much!",
    },
    {
      id: "lifesaver",
      name: "Life Saver",
      type: "rare",
      kind: "hand",
      creator: "Theocharis",
      story:
        "That item saved lots of lives, surfers falling down without knowing how to swim... Why did they even surf if they didn't know how to swim... Ah that makes that item less valuable.. anyways its a rare.",
    },
    {
      id: "kiddingmeme",
      name: "Kidding Meme",
      type: "rare",
      kind: "hat",
      creator: "Unknown",
      story: "Are you kidding me? That meme is really funny :)",
    },
    {
      id: "no1fan",
      name: "SS #1 Fan",
      type: "rare",
      kind: "hand",
      creator: "Unknown",
      story:
        "The Stick Surf crazy fans can wear it with pride, as they love this game :)",
    },
    {
      id: "darkblade",
      name: "Dark Blade",
      type: "rare",
      kind: "hand",
      creator: "Unknown",
      story: "This item is cruel D: No much info about it!",
    },
    {
      id: "piratehook",
      name: "Pirate Hook",
      type: "rare",
      kind: "hand",
      creator: "Unknown",
      story:
        "The pirates that steal, scam and hack deserve this to their hands... Filthy badasses!",
    },
    {
      id: "deathfang",
      name: "Death Fang",
      type: "rare",
      kind: "hand",
      creator: "Unknown",
      story:
        "That item is very rare and it is said to be unavailabe to wear? Well its still cool! :O",
    },
    {
      id: "goldenhelmet",
      name: "Golden Helmet",
      type: "normal",
      kind: "hat",
      creator: "Unknown",
      story:
        "A helmet made of gold... It will not help you much in surfing, will it?",
    },
    {
      id: "pluspass",
      name: "Plus Pass",
      type: "premium",
      kind: "pass-card",
      creator: "Theocharis",
      story:
        "This is the first pass-card created for Stick Surf. It gives the owner the privelege to enter +Sectors and be more quiet. Also it gives more benefits generally. You must own it if you can't have the premium or VIP card-passes!",
    },
    {
      id: "prempass",
      name: "Premium Pass",
      type: "premium",
      kind: "pass-card",
      creator: "Theocharis",
      story:
        "This is one of the best cards. It gives you the same priveleges with plus pass, but in addition you can enter the premium lobby, and chill with the nice guys.",
    },
    {
      id: "vippassit",
      name: "VIP Pass",
      type: "premium",
      kind: "pass-card",
      creator: "Theocharis",
      story:
        "This is the best card, achievable by normal players, it gives you the same priveleges with premium pass, but in addition you can add the VIP lobby and chill with the classy players!",
    },
    {
      id: "normalskin",
      name: "Normal Skin",
      type: "normal",
      kind: "skin",
      creator: "Theocharis",
      story: "Just the default skin.",
    },
    {
      id: "orcclaws",
      name: "Orc Claws",
      type: "rare",
      kind: "hand",
      creator: "Sandro Kach.",
      story:
        "Another masterpiece created by Sandro Kach... It is awesome and relaxing to the eye :)",
    },
    {
      id: "lovelyskin",
      name: "Lovely Skin",
      type: "rare",
      kind: "skin",
      creator: "Unknown",
      story:
        "A skin made for those who want to show love through wearing skins, and enjoy watching the color red..",
    },
    {
      id: "thebros",
      name: "The Bros",
      type: "rare",
      kind: "hat",
      creator: "PewDiePie",
      story:
        "A skin made to honor TheBros app on facebook, that uses the Pewds Icon.",
    },
    {
      id: "mousegloves",
      name: "Mouse Gloves",
      type: "rare",
      kind: "hand",
      creator: "Theocharis",
      story:
        "A pair of gloves, created for Mickey Mouse.. as he was playing Stick Surf a lot... But now it is used from all those hamsters out there :3",
    },
    {
      id: "lolface",
      name: "LOL face",
      type: "premium",
      kind: "hat",
      creator: "Unknown",
      story:
        "The lol face :P This item is used everywhere.. Search for its history on google or something,, duh???",
    },
    {
      id: "fuckyeah",
      name: "FuckYeah face",
      type: "premium",
      kind: "hat",
      creator: "Unknown",
      story:
        "This item is used everywhere.. Search for its history on google or something,, duh???",
    },
    {
      id: "cereal",
      name: "Cereal face",
      type: "premium",
      kind: "hat",
      creator: "Unknown",
      story:
        "This item is used everywhere.. Search for its history on google or something,, duh???",
    },
    {
      id: "forever",
      name: "ForeverAlone",
      type: "premium",
      kind: "hat",
      creator: "Unknown",
      story:
        "This item is used everywhere.. Search for its history on google or something,, duh???",
    },
    {
      id: "fuu",
      name: "Fuu FACE",
      type: "premium",
      kind: "hat",
      creator: "Unknown",
      story:
        "This item is used everywhere.. Search for its history on google or something,, duh???",
    },
    {
      id: "trollface",
      name: "Troll Face",
      type: "premium",
      kind: "hat",
      creator: "Unknown",
      story:
        "This item is used everywhere.. Search for its history on google or something,, duh???",
    },
    {
      id: "bluecap",
      name: "Blue Cap",
      type: "rare",
      kind: "hat",
      creator: "Theocharis",
      story: "It was used to reward the people who liked developer's page!",
    },
    {
      id: "warriorhelm",
      name: "Warrior Helmet",
      type: "rare",
      kind: "hat",
      creator: "Theocharis",
      story:
        "A helmet, for all the warriors came from the past and play Stick Surf now...",
    },
    {
      id: "woodenhammer",
      name: "Wooden Hammer",
      type: "normal",
      kind: "hand",
      creator: "Theocharis",
      story:
        "This hammer is displayed in the game Stick Grandpa, created by Stick Surf developers.",
    },
    {
      id: "birdhand",
      name: "Bird in your hand",
      type: "rare",
      kind: "hand",
      creator: "Theocharis",
      story: "That damn bird follows you everywhere, right behind your hand!",
    },
    {
      id: "featherhat",
      name: "Feather Hat",
      type: "rare",
      kind: "hat",
      creator: "Unknown",
      story:
        "This hat is feathered. What else do you want to be convinced that it is awesomeeee!?",
    },
    {
      id: "vikinghelm",
      name: "Viking Helmet",
      type: "rare",
      kind: "hat",
      creator: "Unknown",
      story: "Created for the first viking ever played Stick Surf!",
    },
    {
      id: "tsunami",
      name: "Tsunami",
      type: "rare",
      kind: "nothing",
      creator: "Unknown",
      story: "There are roumors that it used to be a powerup?!",
    },
    {
      id: "gifthead",
      name: "Gift Head",
      type: "normal",
      kind: "nothing",
      creator: "Unknown",
      story:
        "People needed an item to trade without giving anything, so we made this box, that includes nothing!",
    },
    {
      id: "dragonbow",
      name: "Dragon Bow",
      type: "rare",
      kind: "hand",
      creator: "Sandro Kach.",
      story:
        "One of Sandro's masterpieces, whoever owns it is AWESOMEEEEEEEEEEEE",
    },
    {
      id: "dragonhelm",
      name: "Dragon Helmet",
      type: "rare",
      kind: "hand",
      creator: "Sandro Kach.",
      story:
        "One of Sandro's masterpieces, whoever owns it is AWESOMEEEEEEEEEEEE",
    },
    {
      id: "reindeerhat",
      name: "Reindeer Hat",
      type: "rare",
      kind: "hat",
      creator: "Theocharis",
      story:
        "This item existed long time ago and is believed to be the best xmas item ever created, REINDEERS M8",
    },
    {
      id: "deluxeit",
      name: "The VIP Package",
      type: "deluxe",
      kind: "pack",
      creator: "Theocharis",
      story:
        "The package that includes VIP pack and a random item. If you own it you will get a popup to unlock it and be VIP. The VIP can enter VIP sectors and talk Yellow. Also their rank is setted up to the VIP rank.",
    },
    {
      id: "randomitem",
      name: "The random box?!",
      type: "premium",
      kind: "pack",
      creator: "Theocharis",
      story:
        "This package includes a random item. It can give you better or worse than its price.",
    },
    {
      id: "vipbadgeit",
      name: "The VIP BADGE",
      type: "premium",
      kind: "badge",
      creator: "Theocharis",
      story:
        "This badge is owned by the VIP members. Its so cooooooooooooooooooooooooool!",
    },
    {
      id: "nobirds",
      name: "No Birds!",
      type: "normal",
      kind: "passive-skill",
      creator: "Theocharis",
      story:
        "This skill reduces the possibility to face a bird incoming! (They are the bad guys in every singleplayer game!",
    },
    {
      id: "mummy",
      name: "Mummy Face",
      type: "premium",
      kind: "hat",
      creator: "Unknown",
      story: "This face makes you a mummy... m8 youre dead or smth?!",
    },

    {
      id: "scythe",
      name: "Scythe",
      type: "premium",
      kind: "hand",
      creator: "Sandro Kach.",
      story:
        "One of Sandro's masterpieces, whoever owns it is AWESOMEEEEEEEEEEEE",
    },
    {
      id: "guardian",
      name: "Guardian Angel",
      type: "normal",
      kind: "passive-powerup",
      creator: "Theocharis",
      story:
        "This item is used to revive you one time if you die in Singleplayer Game. It can be reused in the next round you play but only once in a round.",
    },
    {
      id: "captainamericashield",
      name: "Captain America Shield",
      type: "rare",
      kind: "hand",
      creator: "Unknown",
      story:
        "A shield to honor captain america! huehuehuehuehuehuehuehuehuehuehuehuehuehuehuehuehue!",
    },
    {
      id: "captainamericahelmet",
      name: "Captain America Helmet",
      type: "rare",
      kind: "hat",
      creator: "Unknown",
      story:
        "A helmet to honor captain america! huehuehuehuehuehuehuehuehuehuehuehuehuehuehuehuehue!",
    },
    {
      id: "lawl",
      name: "LAWL Face",
      type: "rare",
      kind: "hat",
      creator: "Unknown",
      story: "A really nice meme, showing the face of a lawl guy xD. ",
    },
    {
      id: "thorhammer",
      name: "Thor Hammer",
      type: "rare",
      kind: "hand",
      creator: "Unknown",
      story:
        "The hammer of Thor. This item is a very special item because it used to belong to Thor.",
    },
    {
      id: "thorhelm",
      name: "Thor Helmet",
      type: "rare",
      kind: "hat",
      creator: "Unknown",
      story:
        "The helmet of Thor. This item is a very special item because it used to belong to Thor.",
    },
    {
      id: "sharksb",
      name: "Shark Surfboard",
      type: "rare",
      kind: "surfboard",
      creator: "Unknown",
      story:
        "The sharks was very annoying in the previous singleplayer modes, and it was removed. As a result it should be remained in our memories, so this item was created to seal this memory.",
    },
    {
      id: "watchin",
      name: "Watchin' you meme!",
      type: "premium",
      kind: "hat",
      creator: "Unknown",
      story: "Another funny meme!",
    },
    {
      id: "proskin",
      name: "PRO Skin",
      type: "premium",
      kind: "skin",
      creator: "Theocharis",
      story:
        "A skin created to honor the pro players of Stick Surf. It was in the premium shop before the blue tokens was released, and when they was released the price changed to blue tokens from $",
    },
    {
      id: "matrix",
      name: "Matrix Skin",
      type: "premium",
      kind: "skin",
      creator: "Theocharis",
      story:
        "A skin created for the matrix movie fans :) It is really nice to own it. 01010100101010101010101001010",
    },
    {
      id: "goggles",
      name: "Goggles",
      type: "normal",
      kind: "eye",
      creator: "Unknown",
      story:
        "The first eye-like item for Stick Surf, it is used to watch better when you fall and sharks try to kill you:O",
    },
    {
      id: "angrybirdsmouth",
      name: "AngryBirds mouth",
      type: "premium",
      kind: "mouth",
      creator: "Unknown",
      story:
        "The first mouth-like item for Stick Surf,and awesomely an item from Angry Birds!",
    },
    {
      id: "angrybirdseyes",
      name: "AngryBirds eyes",
      type: "premium",
      kind: "eye",
      creator: "Unknown",
      story: "Awesomely an item from Angry Birds!",
    },
    {
      id: "sunnyglasses",
      name: "Sunny Glasses",
      type: "rare",
      kind: "eye",
      creator: "Unknown",
      story: "The first rare eye-like item for Stick Surf!",
    },
    {
      id: "favourbox",
      name: "Favour Box",
      type: "rare",
      kind: "nothing",
      creator: "Unknown",
      story:
        "This item is similar to the normal gifthead item but this one is more valuable, and if someone donates you here.. its like you donate him:P",
    },
    {
      id: "wolvhead",
      name: "Wolverine Mask",
      type: "premium",
      kind: "hat",
      creator: "Unknown",
      story:
        "This item is made to honor the Wolverine Movie, which is awesomeee!",
    },
    {
      id: "wolvhand",
      name: "Wolverine Nails",
      type: "premium",
      kind: "hand",
      creator: "Unknown",
      story:
        "This item is made to honor the Wolverine Movie, which is awesomeee!",
    },
    {
      id: "marakes",
      name: "Marakes",
      type: "premium",
      kind: "hand",
      creator: "Unknown",
      story:
        "The first animated hand-like item for Stick Surf. Those shits shake!",
    },
    {
      id: "fsskin",
      name: "Fly And Smash Skin",
      type: "legacy",
      kind: "skin",
      creator: "Unknown",
      story:
        "An item for Fly And Smash game. If you have this skin, then you must have played Fly and smash once! Check it out.",
    },
    {
      id: "redarmy",
      name: "Red Army Hat",
      type: "premium",
      kind: "hat",
      creator: "Unknown",
      story: "An item to honor the red army!",
    },
    {
      id: "darkeyes",
      name: "Dark Eyes",
      type: "rare",
      kind: "eye",
      creator: "Unknown",
      story: "Those eyes are so dark and awesome, that makes you look swaggy!",
    },
    {
      id: "legendaryarmy",
      name: "Legendary Army",
      type: "rare",
      kind: "hat",
      creator: "Unknown",
      story: "This hat is made to honor the legendary army!",
    },
    {
      id: "scientistshair",
      name: "Scientists Hair",
      type: "rare",
      kind: "hat",
      creator: "Unknown",
      story:
        "This hat is made for all those scientists who play Stick Surf out there!",
    },
    {
      id: "likerskin",
      name: "Liker Skin",
      type: "premium",
      kind: "skin",
      creator: "Unknown",
      story: "This skin was created for those who liked the Stick Surf page!",
    },
    {
      id: "darksbx",
      name: "Dark Surfboard",
      type: "deluxe",
      kind: "surfboard",
      creator: "Unknown",
      story:
        "This surfboard was created to be the best, though new surfboards was improved and better!",
    },
    {
      id: "bowskin",
      name: "Bow Skin",
      type: "deluxe",
      kind: "skin",
      creator: "Sandro Kach.",
      story:
        "If you own dragon bow and dragon helmet , you are automatically allowed to wear this skin in your inventory!",
    },
    {
      id: "cruel",
      name: "Cruel Muzzle",
      type: "deluxe",
      kind: "eye",
      creator: "Unknown",
      story:
        "Thats one of the 3 items shared for free back in the days, but now are valuable!",
    },
    {
      id: "mjg",
      name: "MJ Gloves",
      type: "deluxe",
      kind: "hand",
      creator: "Unknown",
      story:
        "Thats one of the 3 items shared for free back in the days, but now are valuable!",
    },
    {
      id: "headbelt",
      name: "Head Belt",
      type: "deluxe",
      kind: "hat",
      creator: "Unknown",
      story:
        "Thats one of the 3 items shared for free back in the days, but now are valuable!",
    },
    {
      id: "drug",
      name: "Drug",
      type: "normal",
      kind: "active-skill",
      creator: "Unknown",
      story:
        "This is a skill, usable in Singleplayer that makes you run faster and when the effect ends, a bombwave is exploded around you killing enemies!",
    },
    {
      id: "boom",
      name: "Boom",
      type: "normal",
      kind: "active-skill",
      creator: "Unknown",
      story:
        "This is a skill, usable in Singleplayer that creates a bombwave which explodes around you killing enemies!",
    },
    {
      id: "penguinskin",
      name: "Penguin Skin",
      type: "deluxe",
      kind: "skin",
      creator: "Unknown",
      story:
        "This skin is awesomeeeee! Purchasable only with $ on the deluxeshop.!",
    },
    {
      id: "safe",
      name: "The Safe",
      type: "legacy",
      kind: "safe",
      creator: "Unknown",
      story: "This is used to store items there with a pin.",
    },
    {
      id: "bgzombie",
      name: "Zombie Deal BG",
      type: "deluxe",
      kind: "dealbg",
      creator: "Unknown",
      story:
        "There are many zombie fans out there, so this background was a must!",
    },
    {
      id: "sstbg",
      name: "SST BG",
      type: "legacy",
      kind: "dealbg",
      creator: "Unknown",
      story: "A dealoffer background for the Stick Surf Team!",
    },
    {
      id: "lawbg",
      name: "LAW BG",
      type: "legacy",
      kind: "dealbg",
      creator: "Unknown",
      story: "A dealoffer background for the Stick Surf Laws!",
    },
    {
      id: "legitbg",
      name: "Legit BG",
      type: "legacy",
      kind: "dealbg",
      creator: "Unknown",
      story: "A dealoffer background for the Stick Surf Legit players!",
    },
    {
      id: "superboard",
      name: "Super Surfboard",
      type: "normal",
      kind: "surfboard",
      creator: "Unknown",
      story: "A very fast surfboard, compared to its price!",
    },
    {
      id: "yellowglasses",
      name: "Yellow Glasses",
      type: "rare",
      kind: "eye",
      creator: "Unknown",
      story: "Colourful Glasses, nothing to show.",
    },
    {
      id: "greenglasses",
      name: "Green Glasses",
      type: "rare",
      kind: "eye",
      creator: "Unknown",
      story: "Colourful Glasses, nothing to show.",
    },
    {
      id: "redglasses",
      name: "Red Glasses",
      type: "rare",
      kind: "eye",
      creator: "Unknown",
      story: "Colourful Glasses, nothing to show.",
    },
    {
      id: "blueglasses",
      name: "Blue Glasses",
      type: "rare",
      kind: "eye",
      creator: "Unknown",
      story: "Colourful Glasses, nothing to show.",
    },
    {
      id: "heroism",
      name: "Heroism",
      type: "normal",
      kind: "passive-skill",
      creator: "Unknown",
      story:
        "When you are playing Singleplayer, with this powerup chosen, you have better stats.",
    },
    {
      id: "moonnails",
      name: "Moon Nails",
      type: "legacy",
      kind: "hand",
      creator: "Unknown",
      story: "This is the first legacy-type item for Stick Surf.",
    },
    {
      id: "moonhat",
      name: "Moon Hat",
      type: "legacy",
      kind: "hat",
      creator: "Unknown",
      story: "This is one of the first legacy-type item for Stick Surf.",
    },
    {
      id: "legacypiratehat",
      name: "Legacy Pirate Hat",
      type: "legacy",
      kind: "hat",
      creator: "Unknown",
      story: "This is one of the first legacy-type item for Stick Surf.",
    },
    {
      id: "umbrella",
      name: "Umbrella",
      type: "legacy",
      kind: "hat",
      creator: "Unknown",
      story: "This is one of the first legacy-type item for Stick Surf.",
    },
    {
      id: "sombrero",
      name: "Sombrero",
      type: "premium",
      kind: "hat",
      creator: "Unknown",
      story: "AAHHH RIBA RIBA RIBA SOLEROROROROORLELELROO! VIVA LA VIDA!",
    },
    {
      id: "200skin",
      name: "200 Skin",
      type: "normal",
      kind: "skin",
      creator: "Unknown",
      story: "A skin used to celebrate the 200,000 players played Stick Surf.",
    },
    {
      id: "lemonhand",
      name: "Lemon",
      type: "normal",
      kind: "hand",
      creator: "Unknown",
      story: "Everybody loves lemon.",
    },
    {
      id: "spikehair",
      name: "Spike Hair",
      type: "normal",
      kind: "hat",
      creator: "Unknown",
      story: "The spikiest hair in Stick Surf, for sure.",
    },
    {
      id: "goldenviking",
      name: "Golden Viking Hat",
      type: "normal",
      kind: "hat",
      creator: "Unknown",
      story:
        "There are powerful vikings, and wealthy vikings, this is for the wealthy ones..!",
    },
    {
      id: "onefeatherhat",
      name: "One Feather Hat",
      type: "normal",
      kind: "hat",
      creator: "Unknown",
      story: "This hat contains one feather, which makes it awesome!",
    },
    {
      id: "summerhair",
      name: "Summer Hair",
      type: "normal",
      kind: "hat",
      creator: "Unknown",
      story: "An item to symbolize Summer :D",
    },
    {
      id: "swimmingmask",
      name: "Swimming Mask",
      type: "premium",
      kind: "eye",
      creator: "Unknown",
      story:
        "You need to swim some times, in order to get back to the board.. right?!",
    },
    {
      id: "picassosb",
      name: "Picasso Surfboard",
      type: "premium",
      kind: "surfboard",
      creator: "Picasso",
      story: "So messed up that everybody knows its Picasso's",
    },
    {
      id: "sunnysb",
      name: "Sunny Surfboard",
      type: "normal",
      kind: "surfboard",
      creator: "Unknown",
      story: "A surfboard for the sun.",
    },
    {
      id: "neonsb",
      name: "Neon Surfboard",
      type: "normal",
      kind: "surfboard",
      creator: "Unknown",
      story: "A surfboard for the neon lovers.",
    },
    {
      id: "coolglasses",
      name: "Cool Glasses",
      type: "normal",
      kind: "eye",
      creator: "Unknown",
      story: "For those who want to remain cool, and surf!",
    },
    {
      id: "helmetofsun",
      name: "Helmet of Sun",
      type: "premium",
      kind: "hat",
      creator: "Unknown",
      story:
        "This is a nice helmet, but if you combine it with a legacy mix, it becomes a better one ^^",
    },
    {
      id: "legacymix",
      name: "Legacy Mix",
      type: "legacy",
      kind: "mixer",
      creator: "Unknown",
      story:
        "You will need this in order to mix and combine a helmet of sun and make it a helmet of lava.",
    },
    {
      id: "superlikerskin",
      name: "Super Liker Skin",
      type: "rare",
      kind: "skin",
      creator: "Unknown",
      story:
        "A skin for those who liked every possible page related to Stick Surf :D",
    },
    {
      id: "plus1skin",
      name: "+1 Skin",
      type: "premium",
      kind: "skin",
      creator: "Unknown",
      story: "A very nice skin, for the love ones",
    },
    {
      id: "titaniumskin",
      name: "Titanium Skin",
      type: "normal",
      kind: "skin",
      creator: "Unknown",
      story: "For them guys who are TITANIUUUUM!",
    },
    {
      id: "longhair",
      name: "Long Hair",
      type: "normal",
      kind: "hat",
      creator: "Unknown",
      story: "Well many surfers do have long hair... right?",
    },
    {
      id: "thugmouth",
      name: "Thug Cigar",
      type: "deluxe",
      kind: "mouth",
      creator: "Unknown",
      story: "For all the thugs out there, surfing all day long!",
    },
    {
      id: "thugeyes",
      name: "Thug Eyes",
      type: "deluxe",
      kind: "eye",
      creator: "Unknown",
      story: "For all the thuglifers out there, surfing all day long!",
    },
    {
      id: "lawskin",
      name: "Law Skin",
      type: "legacy",
      kind: "skin",
      creator: "Unknown",
      story: "For the Law players of Stick Surf.",
    },
    {
      id: "likersurfboard",
      name: "Liker Surfboard",
      type: "rare",
      kind: "surfboard",
      creator: "Unknown",
      story: "For the people who like every post of the SS developer!",
    },
    {
      id: "greensurfboard",
      name: "Green Surfboard",
      type: "normal",
      kind: "surfboard",
      creator: "Unknown",
      story: "Just like the normal surfboard but well, its green.",
    },
    {
      id: "rocketsurfboard",
      name: "Rocket Surfboard",
      type: "premium",
      kind: "surfboard",
      creator: "Unknown",
      story: "A very good, rocket-like surfboard, the cosiest surfboard ever!",
    },
    {
      id: "beard",
      name: "Beard",
      type: "normal",
      kind: "mouth",
      creator: "Unknown",
      story: "Not only santa grows beard. Its not a xmas item.",
    },
    {
      id: "goldbandana",
      name: "Gold Bandana",
      type: "premium",
      kind: "mouth",
      creator: "Unknown",
      story: "A bandana for the golden wealthy fkin rich OGS",
    },
    {
      id: "crazyhair",
      name: "Crazy Hair",
      type: "normal",
      kind: "hat",
      creator: "Unknown",
      story: "The longest hair with spikes to the top. Yep. Seems legit.",
    },
    {
      id: "aquarium",
      name: "Aquarium",
      type: "normal",
      kind: "hat",
      creator: "Unknown",
      story: "Blub blub blub blub blub blub blub.",
    },
    {
      id: "gun",
      name: "Gun",
      type: "normal",
      kind: "active-skill",
      creator: "Unknown",
      story:
        "If you own a gun, you can shoot every 10 seconds in the singleplayer mode!",
    },
    {
      id: "k35likes",
      name: "35k Likes Celebrate Skin",
      type: "normal",
      kind: "skin",
      creator: "Unknown",
      story: "A skill to celebrate the 35k likes on developer's page!",
    },
    {
      id: "frozenhat",
      name: "Frozen Hat",
      type: "premium",
      kind: "hat",
      creator: "Unknown",
      story:
        "That hat is so frozen, that even santa doesnt want to wear it, and he lives in a cold place m8!",
    },
    {
      id: "angelhat",
      name: "Angel Hat",
      type: "premium",
      kind: "hat",
      creator: "Unknown",
      story: "A hat that angels used to wear, but gave them to the Surfers!",
    },
    {
      id: "capitanhat",
      name: "Captain Hat",
      type: "premium",
      kind: "hat",
      creator: "Unknown",
      story: "The captain of the ship. W8 m8 don't go so fast with that boat!",
    },
    {
      id: "normalchest",
      name: "Chest",
      type: "premium",
      kind: "chest",
      creator: "Unknown",
      story: "A little chest containing some items.!",
    },
    {
      id: "blessedchest",
      name: "Blessed Chest",
      type: "premium",
      kind: "chest",
      creator: "Unknown",
      story: "A little chest containing nice items.!",
    },
    {
      id: "turtlesb",
      name: "Turtle Surfboard",
      type: "premium",
      kind: "surfboard",
      creator: "Unknown",
      story: "You can surf upon a turtle, how cute?!",
    },
    {
      id: "adminchest",
      name: "Admin Chest",
      type: "legacy",
      kind: "chest",
      creator: "Unknown",
      story:
        "This item gives the admin an oportunity to be rich enough to please his surfers!",
    },
    {
      id: "cookhat",
      name: "Cook Hat",
      type: "premium",
      kind: "hat",
      creator: "Unknown",
      story: "A hat, created for all those Surfers who know how to cook!",
    },
    {
      id: "bloodyaxe",
      name: "Bloody Axe",
      type: "premium",
      kind: "hand",
      creator: "Unknown",
      story: "A axe that contains some blood. EW. DAMN.",
    },
    {
      id: "mphone",
      name: "Microphone",
      type: "premium",
      kind: "hand",
      creator: "Unknown",
      story: "For them surfers who know how to sing.",
    },
    {
      id: "coconut",
      name: "Coconut",
      type: "premium",
      kind: "hand",
      creator: "Unknown",
      story: "For them surfers who enjoy coconuts.",
    },
    {
      id: "trident",
      name: "Trident",
      type: "premium",
      kind: "hand",
      creator: "Unknown",
      story: "The trident of Poseidon. Very nice , very very nice.",
    },
    {
      id: "fishingrod",
      name: "Fishing Rod",
      type: "premium",
      kind: "hand",
      creator: "Unknown",
      story: "Why not catch some fish while surfing, huh?",
    },
    {
      id: "soldierbg",
      name: "Soldier dealBG",
      type: "deluxe",
      kind: "dealbg",
      creator: "Unknown",
      story: "The surfing-dealers who was once soldiers should use this.",
    },
    {
      id: "fisherbg",
      name: "Fisher dealBG",
      type: "premium",
      kind: "dealbg",
      creator: "Unknown",
      story: "The surfing-dealers who enjoy fishing should use this.",
    },
    {
      id: "fnsbg",
      name: "Fly And Smash dealBG",
      type: "rare",
      kind: "dealbg",
      creator: "Giorgi Tshk.",
      story:
        "That dealbg is at the inventories of people who like Fly AND SMASH!",
    },
    {
      id: "mccap",
      name: "Mc Cap",
      type: "deluxe",
      kind: "hat",
      creator: "Theocharis",
      story: "Every McDonalds lover gets it!",
    },
    {
      id: "castlebg",
      name: "Castle Deal BG",
      type: "rare",
      kind: "dealbg",
      creator: "Theocharis",
      story:
        "If you want to have a castle, you can start by having a castle deal bg!",
    },
    {
      id: "mcfries",
      name: "Mc Fries",
      type: "deluxe",
      kind: "hand",
      creator: "Ivan",
      story: "Every McDonalds lover gets it!",
    },
    {
      id: "mcskin",
      name: "Mc Skin",
      type: "deluxe",
      kind: "skin",
      creator: "Ivan",
      story: "Owning the McCap and McFries gets you able to wear this skin!",
    },
    {
      id: "swagglasses",
      name: "Swag Glasses",
      type: "legacy",
      kind: "eye",
      creator: "Theocharis",
      story: "This pair of glasses gives you unlimited swag.",
    },
    {
      id: "headbandana",
      name: "Head Bandana",
      type: "premium",
      kind: "hat",
      creator: "Theocharis",
      story: "Wear it to the head, its a bandana!",
    },
    {
      id: "dailybg",
      name: "Daily Bg",
      type: "legacy",
      kind: "dealbg",
      creator: "Theocharis",
      story: "Stick Surf Daily page owners own that.",
    },
    {
      id: "dailyskin",
      name: "Daily Skin",
      type: "legacy",
      kind: "skin",
      creator: "Theocharis",
      story: "Stick Surf Daily page owners own that.",
    },
    {
      id: "zombiemouth",
      name: "Zombie Mouth",
      type: "rare",
      kind: "mouth",
      creator: "Theocharis",
      story: "Zombieeeeeeeeeeeeeeeeeeeeeeeeeeeees!",
    },
    {
      id: "zombieeyes",
      name: "Zombie Eyes",
      type: "rare",
      kind: "eye",
      creator: "Theocharis",
      story: "Zombieeeeeeeeeeeeeeeeeeeeeeeeeeeees!",
    },
    {
      id: "parrothat",
      name: "Parrot Hat",
      type: "rare",
      kind: "hat",
      creator: "Theocharis",
      story:
        "Parrot, parrot, parrot. Don't resay what I say, resay what I say, what I say, I say, say!",
    },
    {
      id: "flashsurfboard",
      name: "Flash Surfboard",
      type: "premium",
      kind: "surfboard",
      creator: "Theocharis",
      story: "Fast like lightning!",
    },
    {
      id: "shoutred",
      name: "Red Shout",
      type: "premium",
      kind: "shout",
      creator: "Theocharis",
      story: "Type /'redtype:' in front of your text and red chat will appear!",
    },
    {
      id: "wavedsb",
      name: "Waved Surfboard",
      type: "unique",
      kind: "surfboard",
      creator: "Hamsters",
      story:
        "A priceless masterpiece of a surfboard. Blessed by any God. This refined surfboard is one of a kind, and there can't be 2 people having it at the same time.",
    },
    {
      id: "greensharksb",
      name: "Green Shark Surfboard",
      type: "unique",
      kind: "surfboard",
      creator: "Birds",
      story:
        "A priceless masterpiece of a surfboard. Blessed by any God. This refined surfboard is one of a kind, and there can't be 2 people having it at the same time.",
    },
    {
      id: "uniqueskin",
      name: "Unique Skin",
      type: "unique",
      kind: "skin",
      creator: "Kemal",
      story:
        "A priceless masterpiece of a skin. Blessed by any God. This refined skin is one of a kind, and there can't be 2 people having it at the same time.",
    },
    {
      id: "musicskin",
      name: "Music Skin",
      type: "unique",
      kind: "skin",
      creator: "Kemal",
      story:
        "A priceless masterpiece of a skin. Blessed by any God. This refined skin is one of a kind, and there can't be 2 people having it at the same time.",
    },
    {
      id: "natsuhair",
      name: "Natsu Hair",
      type: "unique",
      kind: "hat",
      creator: "Unknown",
      story:
        "A priceless masterpiece of a hair. Blessed by any God. This refined hair is one of a kind, and there can't be 2 people having it at the same time.",
    },
    {
      id: "angelwings",
      name: "Angel Wings",
      type: "normal",
      kind: "wings",
      creator: "Unknown",
      story: "The first wings released in Stick Surf.",
    },
    {
      id: "archangelwings",
      name: "Archangel Wings",
      type: "premium",
      kind: "wings",
      creator: "Unknown",
      story: "The first premium wings released in Stick Surf.",
    },
    {
      id: "guardianwings",
      name: "Guardian Wings",
      type: "legacy",
      kind: "wings",
      creator: "Unknown",
      story: "The first legacy wings released in Stick Surf.",
    },
    {
      id: "devilwings",
      name: "Devil Wings",
      type: "deluxe",
      kind: "wings",
      creator: "Unknown",
      story: "The first deluxe wings released in Stick Surf.",
    },
    {
      id: "deviltrident",
      name: "Devil Trident",
      type: "deluxe",
      kind: "hand",
      creator: "Unknown",
      story: "A trident of a devil. Very valuable!!",
    },
    {
      id: "devilhorns",
      name: "Devil Horns",
      type: "deluxe",
      kind: "hat",
      creator: "Unknown",
      story: "Reward to people unfairly banned.",
    },
    {
      id: "mechanicwings",
      name: "Mechanic Wings",
      type: "unique",
      kind: "wings",
      creator: "Unknown",
      story:
        "The first unique wings released on Stick Surf. A priceless masterpiece of a wing-pair. Blessed by any God. This refined wing-pair is one of a kind, and there can't be 2 people having it at the same time.",
    },
    {
      id: "kiritosword",
      name: "Kirito Sword",
      type: "unique",
      kind: "hand",
      creator: "Unknown",
      story:
        "The first unique sword released on Stick Surf. A priceless masterpiece of a sword. Blessed by any God. This refined sword is one of a kind, and there can't be 2 people having it at the same time.",
    },
    {
      id: "bigdrug",
      name: "Big Drug",
      type: "unique",
      kind: "hand",
      creator: "Unknown",
      story:
        "The first unique drug released on Stick Surf. A priceless masterpiece of a drug. Blessed by any God. This refined drug is one of a kind, and there can't be 2 people having it at the same time.",
    },
    {
      id: "zarichesword",
      name: "Zariche Sword",
      type: "unique",
      kind: "hand",
      creator: "Unknown",
      story:
        "A priceless masterpiece of a sword. Blessed by any God. This refined sword is one of a kind, and there can't be 2 people having it at the same time.",
    },
    {
      id: "akamanahsword",
      name: "Akamanah Sword",
      type: "unique",
      kind: "hand",
      creator: "Unknown",
      story:
        "A priceless masterpiece of a sword. Blessed by any God. This refined sword is one of a kind, and there can't be 2 people having it at the same time.",
    },
    {
      id: "butterflywings",
      name: "Butterfly Wings",
      type: "deluxe",
      kind: "wings",
      creator: "Unknown",
      story: "The most beautiful wings, make you look like a pretty butterfly!",
    },
    {
      id: "dragonwings",
      name: "Dragon Wings",
      type: "normal",
      kind: "wings",
      creator: "Unknown",
      story: "The only dragon-type wings, make you look like a creepy dragon!",
    },
    {
      id: "shadowwings",
      name: "Shadow Wings",
      type: "unique",
      kind: "wings",
      creator: "Unknown",
      story:
        "A priceless masterpiece of a wing-pair. Blessed by any God. This refined wing-pair is one of a kind, and there can't be 2 people having it at the same time.",
    },
    {
      id: "egypthat",
      name: "Egypt Hat",
      type: "premium",
      kind: "hat",
      creator: "Unknown",
      story: "A very nice hat, made in Egypt!",
    },
    {
      id: "egyptsunscepter",
      name: "Egypt Scepter",
      type: "premium",
      kind: "hand",
      creator: "Unknown",
      story: "A very nice scepter, made in Egypt!",
    },
    {
      id: "brosskin",
      name: "The Bros Skin",
      type: "legacy",
      kind: "skin",
      creator: "Unknown",
      story: "The owners of the Bros Stick Surf page owns this.",
    },
    {
      id: "minigun",
      name: "The Minigun",
      type: "deluxe",
      kind: "hand",
      creator: "Unknown",
      story: "Pew pew. Minigun.",
    },
    {
      id: "amusingsword",
      name: "Amusing Sword",
      type: "unique",
      kind: "hand",
      creator: "Unknown",
      story:
        "The Amusing Sword is the most valuable unique. This is the only unique that will be animated. This unique deserves all the rest uniques together! Blessed by universe!",
    },
    {
      id: "aresminigun",
      name: "Ares Minigun",
      type: "unique",
      kind: "hand",
      creator: "Unknown",
      story:
        "The minigun of Ancient Greece's god of war 'Ares'. This minigun is priceless. Only one can have it.",
    },
    {
      id: "rainbowcolor",
      name: "Rainbow Name",
      type: "deluxe",
      kind: "namecolor",
      creator: "Unknown",
      story: "Owning this item will make your name look rainbow in marketplace.",
    },
    {
      id: "drinkablecoconut",
      name: "Drinkable Coconut",
      type: "premium",
      kind: "hand",
      creator: "Unknown",
      story: "A refined coconut, which is drinkable.",
    },
    {
      id: "fairywings",
      name: "Fairy Wings",
      type: "premium",
      kind: "wings",
      creator: "Unknown",
      story: "The wings of a fairy.",
    },
    {
      id: "anchorhat",
      name: "Anchor Hat",
      type: "premium",
      kind: "hat",
      creator: "Unknown",
      story: "Having an anchor on your face feels somehow!?",
    },
    {
      id: "fishermanhat",
      name: "Fisherman Hat",
      type: "premium",
      kind: "hat",
      creator: "Unknown",
      story: "The hat of a fisherman.",
    },
    {
      id: "normalscroll",
      name: "Normal Scroll",
      type: "premium",
      kind: "scrolls",
      creator: "Unknown",
      story: "Use it to enhance your surfer in 50% chance.",
    },
    {
      id: "blessedscroll",
      name: "Blessed Scroll",
      type: "premium",
      kind: "scrolls",
      creator: "Unknown",
      story: "Use it to enhance your surfer in 60% chance.",
    },
    {
      id: "legendaryscroll",
      name: "Legendary Scroll",
      type: "deluxe",
      kind: "scrolls",
      creator: "Unknown",
      story: "Use it to enhance your surfer in 100% chance.",
    },
    {
      id: "axeofthesharkheadhunter",
      name: "Axe of the Shark Headhunter",
      type: "deluxe",
      kind: "hand",
      creator: "Unknown",
      story:
        "There were always roumors about who actually stopped the sharks from coming out. It was the shark headhunter. This axe is in his memory.",
    },
    {
      id: "keyoflaw",
      name: "Key of Law",
      type: "legacy",
      kind: "key",
      creator: "Unknown",
      story: "This key is used to make you law from VIP.",
    },
    {
      id: "keyofteam",
      name: "Key of Team",
      type: "unique",
      kind: "key",
      creator: "Unknown",
      story: "This key is used to make you Team from LAW.",
    },
    {
      id: "beard2015",
      name: "2015 Xmas Beard",
      type: "legacy",
      kind: "mouth",
      creator: "Unknown",
      story:
        "The 2015 xmas items, aren't like the last years items. They are valuable and hard-to-get!",
    },
    {
      id: "winter2015",
      name: "2015 Winter Hat",
      type: "legacy",
      kind: "hat",
      creator: "Unknown",
      story:
        "The 2015 xmas items, aren't like the last years items. They are valuable and hard-to-get!",
    },
    {
      id: "glasses2015",
      name: "2015 Glasses",
      type: "legacy",
      kind: "eye",
      creator: "Unknown",
      story:
        "The 2015 xmas items, aren't like the last years items. They are valuable and hard-to-get!",
    },
    {
      id: "bg2015",
      name: "2015 Deal BG",
      type: "legacy",
      kind: "dealbg",
      creator: "Unknown",
      story:
        "The 2015 xmas items, aren't like the last years items. They are valuable and hard-to-get!",
    },
    {
      id: "terminatorskin",
      name: "Terminator Skin",
      type: "deluxe",
      kind: "skin",
      creator: "Kerolos",
      story:
        "The skin of a terminator. To equip it you must own terminator sword and terminator helmet.",
    },
    {
      id: "terminatorsword",
      name: "Terminator Sword",
      type: "deluxe",
      kind: "hand",
      creator: "Kerolos",
      story: "The sword of a terminator..",
    },
    {
      id: "terminatorhelmet",
      name: "Terminator Helmet",
      type: "deluxe",
      kind: "hat",
      creator: "Kerolos",
      story: "The helmet of a terminator..",
    },
    {
      id: "divinggoggles",
      name: "Diving Goggles",
      type: "normal",
      kind: "eye",
      creator: "Ivan",
      story: "The goggles of a diver.",
    },
    {
      id: "divingbreather",
      name: "Diving Breather",
      type: "normal",
      kind: "mouth",
      creator: "Ivan",
      story: "The breather of a diver.",
    },
    {
      id: "phoenixskin",
      name: "Phoenix Skin",
      type: "premium",
      kind: "skin",
      creator: "Theocharis",
      story:
        "This skin is a skin purchasable in premium shop with blue tokens. If you are VIP and you have this skin plus 10,000 blue tokens then you can upgrade to a Phoenix! Your text colour will be red :O!",
    },
    {
      id: "arcticwolfhead",
      name: "Arctic Wolf Head",
      type: "premium",
      kind: "hat",
      creator: "Theocharis",
      story:
        "Purchasable in premium shop with blue tokens! The winter of 2015-ending is so cold! The arctic wolves came out and hunt for surfers, luckily the Stick Surf Team cut their heads and made them items!",
    },
    {
      id: "arcticwolfnails",
      name: "Arctic Wolf Nails",
      type: "premium",
      kind: "hand",
      creator: "Theocharis",
      story:
        "Purchasable in premium shop with blue tokens! The winter of 2015-ending is so cold! The arctic wolves came out and hunt for surfers, luckily the Stick Surf Team cut their heads and made them items!",
    },
    {
      id: "powergloves",
      name: "Power Gloves",
      type: "deluxe",
      kind: "hand",
      creator: "Sandro Kach.",
      story:
        "A fine masterpiece, created by Sandro Kach. It is purchasable in deluxe shop with 1.59$ That pair of gloves is so large that you look so powerfully awesome!",
    },
    {
      id: "arcticwolfskin",
      name: "Arctic Wolf Skin",
      type: "premium",
      kind: "skin",
      creator: "Theocharis",
      story:
        "The skin a surfer has, only if he owns both of the parts of the Arctic Wolf Set(Head and Nails)!",
    },
    {
      id: "maskofzariche",
      name: "Mask Of Zariche",
      type: "unique",
      kind: "hat",
      creator: "Theocharis",
      story:
        "An ancient warrior, was proven a Holy Hero, because his helmet was found with his skull and even his teeth, on a beach. It is believed that the war he was through was the Trojan War. Everyone think he is Zariche!",
    },
    {
      id: "akskin",
      name: "AK-47 Skin",
      type: "legacy",
      kind: "skin",
      creator: "Theocharis",
      story:
        "Some kamikazis deported on a beach with surfers, and stole their blue tokens, but when they left they forgot a backpack full of ak-47s back in the beach... The surfers got them and sold them to get their things back. Unfortunately, there are only few of those as the ak47s in the bag were few, so this item became legacy, because its very rare.",
    },
    {
      id: "invisibilityhat",
      name: "Invisibility Hat",
      type: "legacy",
      kind: "hat",
      creator: "Theocharis",
      story:
        "This hat, gives the oportunity to the owner to be invisible in sector, not if he wears it but if he only owns it!",
    },
    {
      id: "pedobear",
      name: "Pedobear",
      type: "premium",
      kind: "hat",
      creator: "Sandro Kach.",
      story:
        "This mask of a pedo-bear gives you such an awesome look. You look so magnificent, you know what Im sayin? This is just awesome! Masterpiece! Great! Ferocious! Intelligent! Precious!!!",
    },
    {
      id: "gloves2015",
      name: "Winter Gloves",
      type: "legacy",
      kind: "hand",
      creator: "Olive",
      story:
        "Brrr. Find a fireplace, cuz its so cold. And if you don't find one, your hands are gonna FREEZE! ... Actually you can do something! Wear these gloves and the cold will rush away ^^",
    },
    {
      id: "championmask",
      name: "Champion Mask",
      type: "legacy",
      kind: "hat",
      creator: "Giorgi",
      story:
        "An item that is given as a reward to every Champion Division player, or more, instantly.",
    },
    {
      id: "piratedbg",
      name: "Pirate Deal BG",
      type: "rare",
      kind: "dealbg",
      creator: "Ivan Michael",
      story:
        "An awesome deal background, created by Ivan Michael, a Stick Surf player! This is awesome item and only the people who invite friends can get it!",
    },
    {
      id: "renameitem",
      name: "Rename Item",
      type: "deluxe",
      kind: "service",
      creator: "Theocharis",
      story:
        "With this item, you can change your name and make it as you want! You can use letters, numbers and the special symbols ! and $. In front of your name there will be a @ so people know you changed it, and your name will be still visible in your playercard!",
    },
    {
      id: "sb2015",
      name: "Winter Surfboard",
      type: "legacy",
      kind: "surfboard",
      creator: "Martin Ashwill",
      story:
        "Brrrrrrrrr. Its so cold!!!! We need a thermo-board :P. This surfboard makes ur feet warm!",
    },
    {
      id: "keffiyeh",
      name: "Keffiyeh",
      type: "unique",
      kind: "hat",
      creator: "Kerolos",
      story:
        "A hat that Alladin was wearing while he was taking place in Surfers Tournament in Ancient Egypt! It is said that this cap is pure diamond and it worths tons of bts! Only one can own it!",
    },
    {
      id: "lasereyes",
      name: "Laser Eyes",
      type: "premium",
      kind: "eye",
      creator: "Kerolos",
      story: "See the waves better, feel the flow.",
    },
    {
      id: "diamondsb",
      name: "Diamond Surfboard",
      type: "unique",
      kind: "surfboard",
      creator: "Olive",
      story:
        "The best unique surfboard. Made out of pure diamond and gives the owner special statistics ingame (+9 speed, +6 gravity). It is said that this item was built by the Gods, sacrificing their fortunes! The diamonds found in any place was consumed for this masterpiece to exist!",
    },
    {
      id: "baiumhat",
      name: "Baium Hat",
      type: "rare",
      kind: "hat",
      creator: "Unknown",
      story:
        "Baium was the best surfer in the tournament organized by the Kingdoms of Zariche and Akamanah. He left his hat as an item, when he passed away!",
    },
    {
      id: "darthvader",
      name: "Darth Vader",
      type: "legacy",
      kind: "hat",
      creator: "Kerolos",
      story:
        "The darth vader mask was created when the Stick Surf Team went to the cinema to watch the Star Wars new movie. They found it under a popcorn! But there was only one, so they could duplicate it less times than they thought... and its a legacy (muchworthy) item!",
    },
    {
      id: "delightfulskin",
      name: "Delightful Skin",
      type: "deluxe",
      kind: "skin",
      creator: "Kerolos",
      story:
        "They can stare at this skin for hours! Man im amazed!... This item was created by god's fantasy.",
    },
    {
      id: "dreadchest",
      name: "Dread Chest",
      type: "legacy",
      kind: "chest",
      creator: "Theocharis",
      story: "Can't find that in shops, can ya!",
    },
    {
      id: "happy2016",
      name: "2016 Deal Background",
      type: "rare",
      kind: "dealbg",
      creator: "Ivan",
      story:
        "An item given to all players who played Stick Surf in New Years Eve 2015 to 2016!",
    },
    {
      id: "firelambhead",
      name: "Firelamb's Head",
      type: "premium",
      kind: "head",
      creator: "Unknown",
      story:
        "The Firelamb was found dead in a beach in new year's first day 1/1/2016! The Stick Surf Team cut its head and made it an item, and also got its pole, and made it as well an item! And now it is a set, own both pole and head to get the skin!",
    },
    {
      id: "firelambpole",
      name: "Firelamb's Pole",
      type: "premium",
      kind: "hand",
      creator: "Unknown",
      story:
        "The Firelamb was found dead in a beach in new year's first day 1/1/2016! The Stick Surf Team cut its head and made it an item, and also got its pole, and made it as well an item! And now it is a set, own both pole and head to get the skin!",
    },
    {
      id: "firelambskin",
      name: "Firelamb's Skin",
      type: "premium",
      kind: "skin",
      creator: "Unknown",
      story: "If you own the firelamb's set, you can wear this skin!",
    },
    {
      id: "corecrossbow",
      name: "Core Crossbow",
      type: "premium",
      kind: "hand",
      creator: "Unknown",
      story:
        "The world's core, broke, giving this item! It is believed to be the best bow-kind item in Stick Surf!",
    },
    {
      id: "coremultilauncher",
      name: "Core Multilauncher",
      type: "deluxe",
      kind: "hand",
      creator: "Unknown",
      story:
        "The world's core, broke, giving this item! It is very cheap for its magnificense!",
    },
    {
      id: "endlesshair",
      name: "Endless Hair",
      type: "rare",
      kind: "hat",
      creator: "Unknown",
      story: "Longest Hair Ever! :O",
    },
    {
      id: "goldentermihelmet",
      name: "Golden Termi. Helm.",
      type: "legacy",
      kind: "hat",
      creator: "Kerolos",
      story: "A terminator helmet, combined with a goldbar!",
    },
    {
      id: "goldentermisword",
      name: "Golden Termi. Sword",
      type: "legacy",
      kind: "hand",
      creator: "Kerolos",
      story: "A terminator sword, combined with a goldbar!",
    },
    {
      id: "bronzecoin",
      name: "Bronze Coin",
      type: "premium",
      kind: "mineral",
      creator: "Theocharis",
      story: "A bronze coin, costs 10 blue tokens!",
    },
    {
      id: "silvercoin",
      name: "Silver Coin",
      type: "premium",
      kind: "mineral",
      creator: "Theocharis",
      story: "A silver coin, costs 50 blue tokens and 5 bronze coins!",
    },
    {
      id: "goldcoin",
      name: "Gold Coin",
      type: "premium",
      kind: "mineral",
      creator: "Theocharis",
      story: "A gold coin, costs 100 blue tokens and 5 silver coins!",
    },
    {
      id: "platcoin",
      name: "Platinum Coin",
      type: "premium",
      kind: "mineral",
      creator: "Theocharis",
      story: "A platinum coin, costs 1000 blue tokens and 5 gold coins!",
    },
    {
      id: "lapis",
      name: "Lapis",
      type: "premium",
      kind: "mineral",
      creator: "Theocharis",
      story: "A lapis mineral, costs 10000 blue tokens and 5 platinum coins!",
    },
    {
      id: "gem",
      name: "Gem",
      type: "premium",
      kind: "mineral",
      creator: "Theocharis",
      story: "A gem mineral, costs 20000 blue tokens and 5 lapises!",
    },
    {
      id: "ruby",
      name: "Ruby",
      type: "premium",
      kind: "mineral",
      creator: "Theocharis",
      story: "A ruby mineral, costs 40000 blue tokens and 10 gems!",
    },
    {
      id: "silverbar",
      name: "Silver Bar",
      type: "premium",
      kind: "mineral",
      creator: "Ivan",
      story: "A mineral, worth of 10 silver coins.",
    },
    {
      id: "goldbar",
      name: "Gold Bar",
      type: "premium",
      kind: "mineral",
      creator: "Ivan",
      story: "A mineral, worth of 10 gold coins.",
    },
    {
      id: "punkhair",
      name: "Punk Hair",
      type: "rare",
      kind: "hat",
      creator: "Ivan",
      story: "A punk surfer, passed away, and let these items for his legacy!",
    },
    {
      id: "punkguitar",
      name: "Punk Guitar",
      type: "rare",
      kind: "hand",
      creator: "Ivan",
      story: "A punk surfer, passed away, and let these items for his legacy!",
    },
    {
      id: "punkwings",
      name: "Punk Wings",
      type: "rare",
      kind: "wing",
      creator: "Ivan",
      story: "A punk surfer, passed away, and let these items for his legacy!",
    },
    {
      id: "basicfish",
      name: "Fish",
      type: "normal",
      kind: "fish",
      creator: "Unknown",
      story: "A normal fish, what you looking at?",
    },

    {
      id: "toxicfish",
      name: "Toxic Fish",
      type: "rare",
      kind: "fish",
      creator: "Unknown",
      story:
        "A toxic fish ^^! It looks cool! It is earnable in scratches and chests!",
    },

    {
      id: "turtlefish",
      name: "Turtle Fish",
      type: "deluxe",
      kind: "fish",
      creator: "Unknown",
      story:
        "The most valuable fish at this time! It looks so awesome, and collects blue tokens easier in fishzone ^^!",
    },

    {
      id: "fabulousfish",
      name: "Fabulous Fish",
      type: "premium",
      kind: "fish",
      creator: "Unknown",
      story:
        "A cool fish, more expensive than most of fishes:3 Its so charming & fabulouss :DD!",
    },
    {
      id: "sharkfish",
      name: "Shark Fish",
      type: "legacy",
      kind: "fish",
      creator: "Unknown",
      story:
        "An awesome fish, shared by administrators. It has less speed than turtle fish tho..",
    },
    {
      id: "archangelichat",
      name: "Archangelic Hat",
      type: "rare",
      kind: "hat",
      creator: "Kerolos",
      story:
        "An archangel had fallen. This is his legacy, left out to the Stick World.",
    },
    {
      id: "eelfish",
      name: "Eel Fish",
      type: "deluxe",
      kind: "fish",
      creator: "Unknown",
      story:
        "An awesome fish, shared by administrators. It has less speed than turtle fish tho..",
    },
    {
      id: "ariel",
      name: "Ariel Mermaid",
      type: "deluxe",
      kind: "fish",
      creator: "Unknown",
      story: "The one and only Ariel, fastest in the fish zone... and sexiest;)",
    },
    {
      id: "kingfish",
      name: "King Fish",
      type: "premium",
      kind: "fish",
      creator: "Olive",
      story: "A king-like fish, for all the worthy players out there!",
    },
    {
      id: "classifiedskin",
      name: "Classified Skin",
      type: "legacy",
      kind: "skin",
      creator: "Theocharis",
      story:
        "A skin purchasable only in clan features with 69.000 blue tokens ONLY by a clan leader in a clan lvl 5+! So expensive skin!",
    },
    {
      id: "pietysb",
      name: "Piety Surfboard",
      type: "premium",
      kind: "surfboard",
      creator: "Olive",
      story: "Pietyyyyyyyyyyyyyyyyyyyyyyyyyyy ^^ 4speed 2jump",
    },
    {
      id: "redribbonchest",
      name: "Red Ribbon Chest",
      type: "deluxe",
      kind: "chest",
      creator: "Theocharis",
      story: "This is located in the deluxe shop. Try your luck getting lapis!",
    },
    {
      id: "pinkribbonchest",
      name: "Pink Ribbon Chest",
      type: "deluxe",
      kind: "chest",
      creator: "Theocharis",
      story: "That's op m8.",
    },
    {
      id: "vldmouth",
      name: "Valentine's Day Mouth",
      type: "legacy",
      kind: "mouth",
      creator: "Olive",
      story:
        "An item given away to many Surfers with love, in 2016's Valentine's Day! <3",
    },
    {
      id: "vldhair",
      name: "Valentine's Day Hair",
      type: "legacy",
      kind: "hat",
      creator: "Olive",
      story:
        "An item given away to many Surfers with love, in 2016's Valentine's Day! <3",
    },
    {
      id: "vldsb",
      name: "Valentine's Day Surfboard",
      type: "legacy",
      kind: "surfboard",
      creator: "Olive",
      story:
        "An item given away to many Surfers with love, in 2016's Valentine's Day! <3",
    },
    {
      id: "vldwings",
      name: "Valentine's Day Wings",
      type: "legacy",
      kind: "wings",
      creator: "Olive",
      story:
        "An item given away to many Surfers with love, in 2016's Valentine's Day! <3",
    },
    {
      id: "vldbow",
      name: "Valentine's Day Bow",
      type: "legacy",
      kind: "hand",
      creator: "Olive",
      story:
        "An item given away to many Surfers with love, in 2016's Valentine's Day! <3",
    },
    {
      id: "netronjetpack",
      name: "Netron Jetpack",
      type: "deluxe",
      kind: "wings",
      creator: "Theocharis",
      story:
        "The most futuristic and awesome wings in Stick Surf. Look like you come from the effin' future!",
    },
    {
      id: "neonfish",
      name: "Neon Fish",
      type: "deluxe",
      kind: "fish",
      creator: "Theocharis",
      story:
        "The most futuristic and awesome fish in Stick Surf. Look like you come from the effin' future! Neooooon ^^. Speed: Just like king fish!",
    },
    {
      id: "glowcap",
      name: "Glow Cap",
      type: "rare",
      kind: "head",
      creator: "Giorgi",
      story:
        "A decent looking cap, given away for people who invite their friends in invite&win!",
    },
    {
      id: "pirateshark",
      name: "Pirate Shark",
      type: "rare",
      kind: "fish",
      creator: "Ivan",
      story:
        "A really awesome shark for fishzone, that makes you look like a coool pirate ;)))",
    },
    {
      id: "footballhelmet",
      name: "Football Helmet",
      type: "premium",
      kind: "head",
      creator: "Ivan",
      story:
        "Part of the Football Set. Own both parts to be able to wear the football skin :D!",
    },
    {
      id: "football",
      name: "Foot Ball",
      type: "premium",
      kind: "hand",
      creator: "Ivan",
      story:
        "Part of the Football Set. Own both parts to be able to wear the football skin :D!",
    },
    {
      id: "legacyswiming",
      name: "Legacy Goggles",
      type: "legacy",
      kind: "eyes",
      creator: "Unknown",
      story: "Those legacy goggles worth at least 5k bts, don't be fooled",
    },
    {
      id: "poseidon",
      name: "Poseidon",
      type: "unique",
      kind: "fish",
      creator: "Ivan and Dustin",
      story:
        "The poseidon, Ancient Greek God. A priceless masterpiece of a fish. Blessed by any God. This refined fish is one of a kind, and there can't be 2 people having it at the same time.",
    },
    {
      id: "poker",
      name: "Poker",
      type: "premium",
      kind: "head",
      creator: "The Internet",
      story:
        "This meme is the most valuable meme in Stick Surf. Cuz the rest are shared a lot for free... :')",
    },
    {
      id: "darkmistletoechest",
      name: "Dark Mistletoe Chest",
      type: "deluxe",
      kind: "chest",
      creator: "Theocharis",
      story:
        "An incredible chest, found in the deluxeshop only. This contains more chests and exclusive items!",
    },
    {
      id: "goblin",
      name: "Goblin Skin",
      type: "legacy",
      kind: "skin",
      creator: "Theocharis",
      story:
        "That skin is so rare tho... Look like a goblin, smell like a goblin, ew gross!",
    },
    {
      id: "sixdogsskin",
      name: "6dogs Skin",
      type: "legacy",
      kind: "skin",
      creator: "Dustin",
      story:
        "This skin is a tribute to a club called 6-dogs, in which the developer called Theocharis had a lovely night. It is limited edition, meaning it won't be shared or sold for a long time after the release.",
    },
    {
      id: "selldivision",
      name: "Sell Division Item",
      type: "legacy",
      kind: "service",
      creator: "Theocharis",
      story:
        "Elias idea to create an item to be required to sell division. This is earnable in scratch it and sold for 0,49$ So that hackers aren't able to win!",
    },
    {
      id: "dj",
      name: "DJ",
      type: "legacy",
      kind: "service",
      creator: "Theocharis",
      story: "Play some mp3s with dat one.",
    },
    {
      id: "sharksword",
      name: "Shark Sword",
      type: "deluxe",
      kind: "hand",
      creator: "Omar&Unknown",
      story: "Shark biting on racist pigs. YOU RACIST!",
    },
    {
      id: "pinkkatana",
      name: "Pink Katana",
      type: "deluxe",
      kind: "hand",
      creator: "Omar&Unknown",
      story:
        "The pinkest item ever. Wtf slice them homophobic pigs!!! SJW united!",
    },
    {
      id: "mythicalsword",
      name: "Mythical Sword",
      type: "deluxe",
      kind: "hand",
      creator: "Omar&Unknown",
      story:
        "The myth says that this sword can cut Stick Run into pieces. Stick Surf is so much better.",
    },
    {
      id: "icysword",
      name: "Icy Sword",
      type: "deluxe",
      kind: "hand",
      creator: "Omar&Unknown",
      story: "Reaches -21323413531degrees celcius !!!!",
    },
    {
      id: "serverbooster",
      name: "Server Booster",
      type: "legacy",
      kind: "skin",
      creator: "AsAhza",
      story: "For those who only boost the discord server",
    },
    {
      id: "deluxechest",
      name: "Deluxe Chest",
      type: "deluxe",
      kind: "chest",
      creator: "Theo",
      story: "By optaining this chest you will have chance of winning deluxescratch netronjetpack eelfish minigun delightfulskin darksbx turtlefish vdaybear bloodyvikinghelmet roboticshark zeusfish",
    },
    {
      id: "deluxelockerchest",
      name: "Deluxe Locker Chest",
      type: "deluxe",
      kind: "chest",
      creator: "Theo",
      story: "By optaining this chest you will get to have 5 deluxe chests",
    },
    {
      id: "zephyrchest",
      name: "Zephyr Chest",
      type: "legacy",
      kind: "chest",
      creator: "Theo",
      story: "By optaining this chest you will have chance of winning legacyscratch neonboard anglerfish penguinhat purplesurfboard pearlguitar legacyswiming",
    },
    {
      id: "bluechest",
      name: "Blue Chest",
      type: "legacy",
      kind: "chest",
      creator: "Theo",
      story: "By optaining this chest you will have chance of winning legacyscratch darthvader legacypiratehat unknownsoldiermask legacymix boredfish deadbandana legacylifesaver seahorse neonboard zephyrchest",
    },
    {
      id: "yellowchest",
      name: "Yellow Chest",
      type: "premium",
      kind: "chest",
      creator: "Theo",
      story: "By optaining this chest you will have chance of winning premiumscratch anchorhat fishermanhat randomitem pluspass fuckyeah friendlyfish kingfish prempass yellowgloves flashsurfboard normalscroll matrix bluechest",
    },
    {
      id: "greenchest",
      name: "Green Chest",
      type: "rare",
      kind: "chest",
      creator: "Theo",
      story: "By optaining this chest you will have chance of winning rarescratch glowcap constructionhat constructionmoustache constructionskin weirdfish wood reindeerhat toxicfish",
    },
    {
      id: "redchest",
      name: "Red Chest",
      type: "normal",
      kind: "chest",
      creator: "Theo",
      story: "By optaining this chest you will have chance of winning normalscratch gifthead snowskin angelwings drug goggles anonmask alienskin xxxpic greenchest",
    },
    {
      id: "deluxescratch",
      name: "Deluxe Scratch",
      type: "deluxe",
      kind: "scratch",
      creator: "Unknown",
      story: "Ability to win any deluxe in game by random",
    },{
      id: "premiumscratch",
      name: "Premium Scratch",
      type: "premium",
      kind: "scratch",
      creator: "Unknown",
      story: "Ability to win any Prem in game by random",
    },{
      id: "rarescratch",
      name: "Rare Scratch",
      type: "rare",
      kind: "scratch",
      creator: "Unknown",
      story: "Ability to win any Rare in game by random",
    },
    {
      id: "legacyscratch",
      name: "Legacy Scratch",
      type: "legacy",
      kind: "scratch",
      creator: "Unknown",
      story: "Ability to win any Legacy in game by random",
    },
  ]
}